from enum import StrEnum

VALIDATION_SPLIT = "validation"
HISTORICAL_HOLDOUT_SPLIT = "historical_holdout"


class Col(StrEnum):
    """Canonical column names used by GridCast datasets and artifacts."""

    TIMESTAMP = "dte_reference_date"
    TARGET = "load_mw"
    PREDICTION = "prediction_mw"
    FOLD = "fold"
    CUTOFF = "cutoff"
    HOUR = "hour"
    WEEKDAY = "weekday"
    DATE = "date"
    MODEL = "model"
    SPLIT = "split"
    TEMPERATURE = "temperature_2m_c"
    P10 = "p10_mw"
    P50 = "p50_mw"
    P90 = "p90_mw"
    P10_CALIBRATED = "p10_calibrated_mw"
    P90_CALIBRATED = "p90_calibrated_mw"
    P10_HOURLY_CALIBRATED = "p10_hourly_calibrated_mw"
    P90_HOURLY_CALIBRATED = "p90_hourly_calibrated_mw"
    P10_ROLLING_CALIBRATED = "p10_rolling_calibrated_mw"
    P90_ROLLING_CALIBRATED = "p90_rolling_calibrated_mw"
    AREA = "area"
    AVAILABLE_AT = "available_at"
    FORECAST_ORIGIN = "forecast_origin"
    LOCATION = "location"
    RUN_INITIALIZED_AT = "run_initialized_at"
    VALID_AT = "valid_at"
