[theme]
base = "light"
primaryColor = "#F05D23"
backgroundColor = "#F4F1EA"
secondaryBackgroundColor = "#E8E2D6"
textColor = "#17242B"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
